### PR TITLE
docs: add terminal process management documentation

### PR DESCRIPTION
**Pull request by gabrielluthun**
### Summary 
_Documentation of the process management on a terminal_
### Details
_This documentation talks about the process management on a Linux Terminal.
You can find here the `ps`, `top`and `htop` commands._

### References 
No reference.
### CHECKS 

- [x] Tested changes

### DISCLAIMER
_This is a v1 of the document. This might be evolving._

### CODE REVIEW

**Review by alf-Meodel — APPROVED** [review]
Hey thx for yoru great contribution !

**Review by YohanF1245 — DISMISSED** [review]
bouh le br

**Review by alf-Meodel — CHANGES_REQUESTED** [review]
NO BR

**Review by alf-Meodel — CHANGES_REQUESTED** [review]
NONONO !!!!! ¯\_༼ ಥ ‿ ಥ ༽_/¯

**Review by alf-Meodel — APPROVED** [review]

**Comment by BborisB** [comment]
C'est fini

**Review by BborisB — APPROVED** [review]
Lu et approuvé

**Pull request merged**
