### PR TITLE
doc(navigation.md): add doc

### PR DESCRIPTION
**Pull request by YohanF1245**
added doc for generic terminal hotkey

### CODE REVIEW

**Review by alf-Meodel — APPROVED** [review]
LGTM! (Looks good to me)
Great work on this! Everything seems to be in order, and the changes align well with the project goals. Approved for merging. 👍

**Review by alf-Meodel — APPROVED** [review]
LGTM! (Looks good to me)
Great work on this! Everything seems to be in order, and the changes align well with the project goals. Approved for merging. 👍

**Review by alf-Meodel — APPROVED** [review]
excellent thank you for your contribution

**Review by alf-Meodel — APPROVED** [review]
excellent thank you for your contribution

**Review by BborisB — APPROVED** [review]
Lu et approuvé

**Review by alf-Meodel — COMMENTED** [review]
Oh THX FOR YOUR CONTRIBUTION NICE WORK

**Pull request merged**
